### ISSUE TITLE
Response protection not correctly chosen

### ISSUE THREAD

**Issue by RufusJWB** [siemens/cmp-ra-component#91]
Note: Issue tracker is **ONLY** used for reporting bugs.

## Issue Report

If a client sends a request message protected with a shared secret the response might be protected with a certificate.

## Expected Behavior

The response should be protected with the shared secret.

## Current Behavior

The response might be protected with a certificate

## Possible Solution

as discussed with @DDvO and @Akretsch

**Comment by RufusJWB** [comment]
@DDvO  and myself stumbled about this problem yesterday again, and it becomes more and more annoying.

**Comment by DDvO** [comment]
The original report was about the cmpRaComponent not fulfilling the following requirement from the LCMPP section 4.1.5:
> The protection of all messages MUST be MAC-based.  Therefore,
       extraCerts fields of all messages do not contain CMP protection
       certificates and associated chains.
       
The additional point that came up yesterday is that when the server receives a request message with MAC-based protection using some shared secret, clearly the response that it sends on this request must be protected using the same shared secret.
Looks like that this is not the case and this this is not even explicitly specified in the LCMPP.

**Comment by HBrock** [comment]
RFC 9483 Section 4.1.5 clearly states "Therefore, the request and response messages are MAC-protected using **this** shared secret information."

**Comment by DDvO** [comment]
Thanks for pointing this out - on Friday I somehow overlooked this sentence.

Anyway, this necessity implies that it makes little sense that the CmpRaComponent and the LightweightCmpRa allow configuring a shared secret in its downstream outputCredentials (which are part of the CmpMessageInterface, described [here](https://github.com/siemens/LightweightCmpRa/tree/main/doc/config#the-cmpmessageinterface-value) or [here](https://github.com/siemens/cmp-ra-component/blob/main/src/main/java/com/siemens/pki/cmpracomponent/configuration/CmpMessageInterface.java), respectively ) because it must use the same secret as the one it used to verify the protection of the request message it received on one of its downstream interfaces and this secret has already been configured in the VerificationContext (which is part of the same CmpMessageInterface).

**Comment by DDvO** [comment]
@RufusJWB please note the following statement in https://github.com/siemens/LightweightCmpRa/tree/main/doc/config#the-cmpmessageinterface-value:

> The current implementation supports only one SharedSecret per VerificationContext. So the only way to specify more than one shared secret per DownstreamConfiguration or UpstreamConfiguration is to use more than one certProfile.

So already when using PBM on receiving a request, only one shared secret per certProfile (and bodyType) is supported,
and due to the just mentioned inherent dependency within the downstream interface regarding the use of shared secrets, this implies that also when protecting response messages only one shared secret per certProfile and bodyType can be supported so far.

**Comment by DDvO** [comment]
Moreover, at LightweightCmpRa level, [the config doc](https://github.com/siemens/LightweightCmpRa/tree/main/doc/config#the-outputcredentials-object) says:

> Note: The configuration does not support specifying both signature-based and MAC-based protection. Consequently, the RA will always protect as configured, even if the (downstream) client uses a different way of protecting its requests. As the Lightweight CMP profile forbids mixing signature-based and MAC-based protection within the same transaction, care needs to be taken such that the EE and RA configurations are consistent for all types of requests. To this end it can be helpful to differentiate via certificate profiles.

For the demo, we can resort to specifying re-protection with the right shared secret for `ip` messages, like this:
```
DownstreamConfiguration:
  - bodyType: ip
    ReprotectMode: reprotect
    OutputCredentials:
      SharedSecret:
        SharedSecret: "myPresharedSecret"
        SenderKID: "sender_RA"
        PasswordBasedMacAlgorithm: "PBM"
    VerificationContext:
      trustedCertificates:
        - "credentials/CMP_EE_Root.pem"
        - "credentials/ENROLL_Root.pem"
      sharedSecret: "myPresharedSecret"
  # for any other bodyType:
  - OutputCredentials:
      Signature:
        keyStore: credentials/CMP_LRA_DOWNSTREAM_Keystore.p12
        password:  Password
    VerificationContext:
      trustedCertificates:
        - "credentials/CMP_EE_Root.pem"
        - "credentials/ENROLL_Root.pem"
      sharedSecret: "myPresharedSecret"
```
